basePath: /
host: localhost:8080
info:
  contact:
    email: support@dauys.com
    name: API Support
  description: This is the backend API for the Online Election system.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://dayus.kz
  title: Online Election Vote
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
