// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://dayus.kz",
        "contact": {
            "name": "API Support",
            "email": "support@dauys.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidate/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Get candidate by ID",
                "parameters": [
                    {
                        "description": "Candidate ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_candidate_routes.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Candidate details",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Candidate not found",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/candidate/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Create a candidate",
                "parameters": [
                    {
                        "description": "Candidate data",
                        "name": "candidate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Candidate created successfully",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/candidate/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Delete a candidate",
                "parameters": [
                    {
                        "description": "Candidate ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_candidate_routes.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Candidate deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/candidate/search": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Search candidates by name",
                "parameters": [
                    {
                        "description": "Search query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_candidate_routes.searchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Query is required",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Search failed",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/candidates": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Get candidates by type",
                "parameters": [
                    {
                        "description": "Candidate Type",
                        "name": "candidateType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_candidate_routes.candidateTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of candidates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/candidates/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Get candidates by type by page",
                "parameters": [
                    {
                        "description": "Candidates By Page",
                        "name": "candidateType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_candidate_routes.candidatesByPageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of candidates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VoteGolang_internals_domain.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates a user and returns access and refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Get all petitions",
                "responses": {
                    "200": {
                        "description": "List of all petitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to get petitions",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Create a petition",
                "parameters": [
                    {
                        "description": "Petition Data",
                        "name": "petition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Petition created successfully",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Delete a petition",
                "parameters": [
                    {
                        "description": "Petition ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_petition_routes.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Petition deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to delete petition",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/id": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Get petition by ID",
                "parameters": [
                    {
                        "description": "Petition ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_petition_routes.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Petition details",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Petition not found",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/page": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Get petitions by page",
                "parameters": [
                    {
                        "description": "Pagination info",
                        "name": "pagination",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internals_controller_petition_routes.PaginationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of petitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid page or limit",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get petitions",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/petition/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Vote on a petition",
                "parameters": [
                    {
                        "description": "Vote request",
                        "name": "petitionVote",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.PetitionVoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote registered",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.Petition"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Voting forbidden (deadline reached or goal met)",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to vote",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Generates a new pair of access and refresh tokens using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Creates a new user account and sends an email verification link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/verify-email": {
            "get": {
                "description": "Verifies the user's email using a token sent in the verification link.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify email address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email verification token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email verified successfully",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Vote for a candidate",
                "parameters": [
                    {
                        "description": "Candidate vote data",
                        "name": "candidate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_domain.VoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote successful",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or duplicate petition",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/VoteGolang_internals_controller_http_response.JSONResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "VoteGolang_internals_controller_http_response.JSONResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "VoteGolang_internals_domain.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "VoteGolang_internals_domain.Candidate": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 20
                },
                "education": {
                    "type": "string",
                    "example": "KBTU"
                },
                "name": {
                    "type": "string",
                    "example": "Beksultan"
                },
                "party": {
                    "type": "string",
                    "example": "Jastar"
                },
                "photo": {
                    "type": "string",
                    "example": "link"
                },
                "region": {
                    "type": "string",
                    "example": "SKO"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/VoteGolang_internals_domain.CandidateType"
                        }
                    ],
                    "example": "manager"
                },
                "voting_deadline": {
                    "type": "string",
                    "example": "2026-11-12T09:00:00+05:00"
                },
                "voting_start": {
                    "type": "string",
                    "example": "2025-11-12T09:00:00+05:00"
                }
            }
        },
        "VoteGolang_internals_domain.CandidateType": {
            "type": "string",
            "enum": [
                "presidential",
                "deputy",
                "manager"
            ],
            "x-enum-varnames": [
                "Presidential",
                "Deputy",
                "Manager"
            ]
        },
        "VoteGolang_internals_domain.Petition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "petition description"
                },
                "goal": {
                    "type": "integer",
                    "example": 0
                },
                "photo": {
                    "type": "string",
                    "example": "link"
                },
                "title": {
                    "type": "string",
                    "example": "petition title"
                },
                "voting_deadline": {
                    "type": "string",
                    "example": "2025-05-10T23:59:00+05:00"
                }
            }
        },
        "VoteGolang_internals_domain.PetitionVoteRequest": {
            "type": "object",
            "properties": {
                "petition_id": {
                    "type": "integer"
                },
                "vote_type": {
                    "description": "Enum values: favor, against",
                    "allOf": [
                        {
                            "$ref": "#/definitions/VoteGolang_internals_domain.VoteType"
                        }
                    ],
                    "example": "favor, against"
                }
            }
        },
        "VoteGolang_internals_domain.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "VoteGolang_internals_domain.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "VoteGolang_internals_domain.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "59, Tole Bi St, Almaty"
                },
                "birthDate": {
                    "type": "string",
                    "example": "2004-07-16T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "zhaslanbeksultan@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "$Password123"
                },
                "roleID": {
                    "type": "integer",
                    "example": 2
                },
                "userFullName": {
                    "type": "string",
                    "example": "Beksultan Zhaslan"
                },
                "username": {
                    "type": "string",
                    "example": "beks"
                }
            }
        },
        "VoteGolang_internals_domain.VoteRequest": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "integer"
                },
                "candidate_type": {
                    "type": "string",
                    "enum": [
                        "presidential",
                        "deputy",
                        "manager"
                    ],
                    "example": "presidential, deputy, manager"
                }
            }
        },
        "VoteGolang_internals_domain.VoteType": {
            "type": "string",
            "enum": [
                "favor",
                "against"
            ],
            "x-enum-varnames": [
                "Favor",
                "Against"
            ]
        },
        "internals_controller_candidate_routes.IDRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internals_controller_candidate_routes.candidateTypeRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "example": "manager"
                }
            }
        },
        "internals_controller_candidate_routes.candidatesByPageRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "type": "string",
                    "example": "manager"
                }
            }
        },
        "internals_controller_candidate_routes.searchRequest": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                }
            }
        },
        "internals_controller_petition_routes.IDRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internals_controller_petition_routes.PaginationRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Online Election Vote",
	Description:      "This is the backend API for the Online Election system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
