// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://dayus.kz",
        "contact": {
            "name": "API Support",
            "email": "support@dauys.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Get candidates by type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Candidate Type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of candidates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/candidate.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/candidates/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Get candidates by type by page",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Candidate Type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of candidates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/candidate.Candidate"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login and get access tokens",
                "parameters": [
                    {
                        "description": "Username and Password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/petition/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Get all petitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/petition.Petition"
                            }
                        }
                    }
                }
            }
        },
        "/petition/all/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Get petitions by page",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/petition.Petition"
                            }
                        }
                    }
                }
            }
        },
        "/petition/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Create a petition",
                "parameters": [
                    {
                        "description": "Petition Data",
                        "name": "petition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/petition.Petition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Petition created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/petition/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petition"
                ],
                "summary": "Vote on a petition",
                "parameters": [
                    {
                        "description": "Petition petition data",
                        "name": "petitionVote",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/petition.PetitionVoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Voted on petition",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Username and Password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User registered successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidates"
                ],
                "summary": "Vote for a candidate",
                "parameters": [
                    {
                        "description": "Candidate vote data",
                        "name": "candidate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/candidate.VoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or duplicate petition",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "candidate.Candidate": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "education": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "party": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/candidate.CandidateType"
                },
                "votes": {
                    "type": "integer"
                },
                "votingDeadline": {
                    "type": "string",
                    "example": "2025-05-10T23:59:00+05:00"
                },
                "votingStart": {
                    "type": "string",
                    "example": "2025-05-10T23:59:00+05:00"
                }
            }
        },
        "candidate.CandidateType": {
            "type": "string",
            "enum": [
                "presidential",
                "deputy",
                "manager"
            ],
            "x-enum-varnames": [
                "Presidential",
                "Deputy",
                "Manager"
            ]
        },
        "candidate.VoteRequest": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "integer"
                },
                "candidate_type": {
                    "type": "string",
                    "enum": [
                        "presidential",
                        "deputy",
                        "manager"
                    ],
                    "example": "presidential, deputy, manager"
                }
            }
        },
        "petition.Petition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "goal": {
                    "type": "integer"
                },
                "photo": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "votingDeadline": {
                    "type": "string",
                    "example": "2025-05-10T23:59:00+05:00"
                }
            }
        },
        "petition.PetitionVoteRequest": {
            "type": "object",
            "properties": {
                "petition_id": {
                    "type": "integer"
                },
                "vote_type": {
                    "description": "Enum values: favor, against",
                    "allOf": [
                        {
                            "$ref": "#/definitions/petition.VoteType"
                        }
                    ],
                    "example": "favor, against"
                }
            }
        },
        "petition.VoteType": {
            "type": "string",
            "enum": [
                "favor",
                "against"
            ],
            "x-enum-varnames": [
                "Favor",
                "Against"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Online Election Vote",
	Description:      "This is the backend API for the Online Election system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
